Algoritmo "03-08-entrada"

Var

   idade : inteiro
   salario : real
   nome : caractere


Inicio


   escreva("Digite seu nome: ")
   leia(nome)
   escreva("Digite sua idade: ")
   leia(idade)
   escreva("Informe seu salário: ")
   leia(salario)
   escreval()
   escreval("Dados Digitados:")
   escreval()
   escreval("Nome = ", nome)
   escreval("Idade = ", idade)
   escreval("Salário = ", salario:8:2)

   


Fimalgoritmo