Algoritmo "03-06-saida"
//  
//  
// Saída de Dados
// escreva(" ")   -  sem quebra de linha
// escreval(" ")  -  com quebra de linha
Var
   a : inteiro
   b : real
   c : caractere
   d : logico


Inicio
      a <- 32
      b <- 2.34567
      c <- " bom dia!"
      d <- VERDADEIRO
      
      escreval(a)
      escreval(b:3:4)
      escreval(c)
      escreva(d)

Fimalgoritmo