Algoritmo "03-03-variaveis"
// Declaração de Variável
// <nome> : <tipo>

// Tipos Básicos
// inteiro
// real
// caractere
// logico


// escreva(var:8:2)
// var = variavel
// 8   = número total de casas que vai ocupar
// 2   = número de casas decimais
Var
   nome : caractere
   a : real
   


Inicio
      a <- 35.7895

      escreva("Escreva seu nome: ")
      leia(nome)
      escreva("Seu nome é:" + nome)
      escreva(a:2:1)


Fimalgoritmo