Algoritmo "03-02 Expressões aritméticas"
// Operadores Aritméticos
// Adição     +
// Sub.       -
// Mult.      *
// Div.       /
// Div Int.   \
// Mod        %
// Pot.       ^
Var



Inicio
      escreva(10 + 2) // 12
      escreva(10 - 2) // 8
      escreva(10 * 2) // 20
      escreva(7 / 2)  // 3.5
      escreva(7 \ 2)  // 3
      escreva(7 % 2)  // 1
      escreva(7 ^ 2)  // 49


Fimalgoritmo